# Generated by Django 5.1.1 on 2024-10-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedurl',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedurl',
            name='url',
            field=models.URLField(),
        ),
    ]
